apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/ch007m/konflux-demo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  labels:
    appstudio.openshift.io/application: konflux-demo
    appstudio.openshift.io/component: konflux-demo
    pipelines.appstudio.openshift.io/type: build
  name: konflux-demo-on-push
  namespace: cmoullia-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/cmoullia-tenant/konflux-demo/konflux-demo:{{revision}}
    - name: dockerfile
      value: Dockerfile
    - name: skip-checks
      value: true
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}